#!/bin/bash
#export CPATH=../include/

cd src

for i in *.asm
do
	echo Assembling $i
    nasm -f elf32 -g -F dwarf -o "../obj/${i%.asm}.asm.o" "$i"
done

for i in *.cpp
do
	echo Compiling $i
    i686-elf-g++ -c "$i" -o "../obj/${i%.cpp}.cpp.o" -I ../include --freestanding -fno-exceptions -fno-rtti -std=c++14 -Wno-write-strings
done

#for i in *.S
#do
#	echo Compiling $i
#    i686-elf-as -c "$i" -o "../obj/${i%.S}.S.o"
#done

for i in *.c
do
	echo Compiling $i
    i686-elf-gcc -c "$i" -o "../obj/${i%.c}.c.o" -I ../include --freestanding
done

cd ..

i686-elf-ld -m elf_i386 -T linkscript.ld -o bin/kernel.sys obj/*.asm.o obj/*.cpp.o obj/*.c.o #obj/*.S.o

