#!/bin/bash
#export CPATH=../include/

cd src

for i in *.cpp
do
	echo Compiling $i
    g++ -c "$i" -o "../obj/x86/${i%.cpp}.o" -m32 -I include -I arch/x86/include --freestanding -fno-exceptions -fno-rtti -std=c++11 -Wno-write-strings
done

cd arch/x86

for i in *.asm
do
	echo Assembling $i
    nasm -f elf32 -g -F dwarf -o "../../../obj/x86/${i%.asm}.asm.o" "$i"
done

for i in *.cpp
do
	echo Compiling $i
    g++ -c "$i" -o "../../../obj/x86/${i%.cpp}.o" -m32 -I include -I ../../include --freestanding -fno-exceptions -fno-rtti -std=c++11 -Wno-write-strings
done

cd ../../../

gcc -lgcc -m32 -T linkscript.ld -o bin/x86/kernel.sys obj/x86/*.o obj/x86/*.asm.o -fno-pic -Wl,--build-id=none -ffreestanding -O2 -nostdlib
